### PR TITLE
Fix error in the test suite

### PR DESCRIPTION
**Pull request by mclements**
This is a minor fix.

$ java -version
java version "1.7.0_91"
OpenJDK Runtime Environment (IcedTea 2.6.3) (7u91-2.6.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.91-b01, mixed mode)

Sincerely, Mark.

### CODE REVIEW

**Comment by mungerd** [comment]
On my workstation, I'm not getting the same output as you.
This means that there are too many decimals in the text output.
To fix the problem, we should limit the number of decimals in the tests outputs.

**Comment by mclements** [comment]
That sounds good. I naively tried to use String.format("%.14g", ni2bObj.computeCorr()), but that didn't work. Can you fix this from your end? Kindly, Mark.

**Comment by mungerd** [comment]
Indeed, that seems to be the right thing to do!
Have you fixed the expected output in `src/main/docs/examples/probdistmulti/norta/ExampleNortaInitDisc.txt` as well?
If this is not the problem, I'll have a look at it later.

**Comment by mclements** [comment]
Good point. I have now added a commit that reduces the precision in the .txt file and used String.format() in the .java file. This works for me. Does it work for you? Kindly, Mark.

**Comment by mclements** [comment]
Out of interest, is it obvious why the values give different answers on different architectures? I had thought that Java numerics were standardised.

**Comment by mungerd** [comment]
Thank you, Mark.
To be future-proof, we should do it for all 4 results, though.  I can do it this afternoon.  If you wish to do it, would you mind crushing it all in a single commit?
I realized I was using Java 1.6.  That's why I had different results.  With Java 1.7 I get the same as you.

**Comment by mungerd** [comment]
Implemented by c100806.  Thank you, @mclements.

**Pull request closed without merging**
